apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{ include "intelliscale.fullname" . }}
  labels: {{- include "intelliscale.labels" . | nindent 4}}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "intelliscale.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        # Force restart on config changes
        checksum/config: {{ tpl .Values.ryax.worker.configMapName . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "intelliscale.labels" . | nindent 8 }}
        app.kubernetes.io/component: "internal"
        ryax.tech/resource-type: "internal"
        ryax.tech/endpoint: "intelliscale-main" # Let service find this pod and not the node labelers.
    spec:
      priorityClassName: {{ .Values.priorityClass }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534 # nobody
      {{- with .Values.imagePullSecrets | default .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: tmptraces-volume
          emptyDir:
            sizeLimit: 1Gi
        - name: {{ include "intelliscale.fullname" . }}-config
          configMap:
            name: {{ include "intelliscale.fullname" . }}-config
        {{- if .Values.ryax.worker.configMapName }}
        - name: site-config
          configMap:
            name: {{ tpl .Values.ryax.worker.configMapName . }}
        {{- end }}
      containers:
        - name: {{ include "intelliscale.fullname" . }}
          image: {{ include "intelliscale.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /tmptraces
              name: tmptraces-volume
            - name: {{ include "intelliscale.fullname" . }}-config
              mountPath: /intelliscale-config
            {{- if .Values.ryax.worker.configMapName }}
            - name: site-config
              mountPath: /site-config
            {{- end }}
          ports:
            - name: api-port
              containerPort: {{ .Values.config.server_ports.api_grpc_server_port }}
            - name: metrics-port
              containerPort: {{ .Values.config.server_ports.metrics_server_port }}
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics-port
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics-port
          env:
            {{- if .Values.ryax.worker.configMapName }}
            - name: RYAX_CONFIG_SITE
              value: /site-config/config.yaml
            {{- end }}
            - name: RYAX_CONFIG_APP
              value: /intelliscale-config/config.yaml
