{{- $secretData := get (lookup "v1" "Secret" .Release.Namespace .Values.brokerSecret) "data" | default dict }}
{{- range tuple .Release.Namespace .Values.global.ryax.userNamespace }}
{{- $brokerPass := get $secretData "rabbitmq-password" | b64dec | default (randAlphaNum 12) }}
apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ $.Values.brokerSecret }}
  labels:
    {{- include "common-resources.labels" $ | nindent 4 }}
  namespace: {{ . }}
stringData:
  broker-user: {{ $.Values.brokerUser }}
  broker: "ampq://{{ $.Values.brokerUser }}:{{ $brokerPass }}@{{ $.Values.brokerService }}.{{ $.Release.Namespace }}:{{ $.Values.brokerPort }}/"
  rabbitmq-password: {{ $brokerPass }}
type: "Opaque"
---
{{- end }}

apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ $.Values.brokerCookieName }}
  labels:
    {{- include "common-resources.labels" $ | nindent 4 }}
data:
  {{- $secretData := get (lookup "v1" "Secret" .Release.Namespace $.Values.brokerCookieName) "data" | default dict }}
  rabbitmq-erlang-cookie: {{ get $secretData "rabbitmq-erlang-cookie" | default (randAlphaNum 30 | b64enc) }}
type: "Opaque"
---
