{{- $secretData := get (lookup "v1" "Secret" .Release.Namespace .Values.filestoreSecret) "data" | default dict }}
{{- $filestorePass := get $secretData "root-password" | b64dec | default (randAlphaNum 12) }}
apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ $.Values.filestoreSecret }}
  labels: {{- include "common-resources.labels" $ | nindent 4 }}
stringData:
  filestore: "{{ $.Values.filestoreService }}.{{ $.Release.Namespace }}:{{ $.Values.filestorePort }}"
  filestore-access: {{ $.Values.filestoreUser }}
  filestore-secret: {{ $filestorePass }}
  root-user: {{ $.Values.filestoreUser }}
  root-password: {{ $filestorePass }}
type: "Opaque"
