# jwt secret
apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ .Values.jwtSecret }}
  labels: {{ include "common-resources.labels" . | nindent 4 }}
type: "Opaque"
data:
  {{- $secretData := get (lookup "v1" "Secret" .Release.Namespace .Values.jwtSecret) "data" | default dict }}
  jwt-secret-key: {{ get $secretData "jwt-secret-key" | default (randAlphaNum 64 | b64enc) }}

{{- if .Values.global.monitoring.enabled }}
---
# grafana credentials
apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ .Values.grafanaSecret }}
  labels: {{ include "common-resources.labels" . | nindent 4 }}
type: "Opaque"
stringData:
  {{- $secretData := get (lookup "v1" "Secret" .Release.Namespace .Values.grafanaSecret) "data" | default dict }}
  admin-user: "ryax"
  admin-password: {{ get $secretData "admin-password" | b64dec | default (randAlphaNum 12) }}
{{- end }}
