apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ .Values.passwordEncryptionKeySecret }}
  labels: {{ include "repository.labels" . | nindent 4 }}
type: "Opaque"
stringData:
  {{- $secretData := get (lookup "v1" "Secret" .Release.Namespace .Values.passwordEncryptionKeySecret) "data" | default dict }}
  encryption-key: {{ get $secretData "encryption-key" | b64dec | default .Values.fernetEncryptionKey | default (randAscii 32 | b64enc) }}
