apiVersion: "v1"
kind: "Service"
metadata:
  name: {{ include "repository.fullname" . }}
  labels: {{- include "repository.labels" . | nindent 4 }}
spec:
  ports:
    - name: "api"
      port: {{ .Values.apiPort }}
  selector: {{- include "repository.selectorLabels" . | nindent 4 }}
