version: '3'

services:
  install-ryax:
    image: "ryax-adm:latest"
    entrypoint: /data/local_ryax/install-ryax.sh
      #entrypoint:
      #  - sleep
      #  - inf
    volumes:
      # This is just so that we get the kubeconfig file in
      - .:/inout
    environment:
      - KUBECONFIG=/inout/kubeconfig.yaml

  k3s-server:
    image: "rancher/k3s:v1.24.10-k3s1"
    command:
      - server
      - --disable=traefik
      - --disable=metrics-server
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
      - K3S_TOKEN=${K3S_TOKEN:?err}
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
    volumes:
      - k3s-server-vol:/var/lib/rancher/k3s
      # This is just so that we get the kubeconfig file out
      - .:/output
    ports:
      - 6443:6443  # Kubernetes API Server
      - 80:80      # Ingress controller port 80
      - 443:443    # Ingress controller port 443

  k3s-agent:
    image: "rancher/k3s:v1.24.10-k3s1"
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
      - K3S_URL=https://k3s-server:6443
      - K3S_TOKEN=${K3S_TOKEN:?err}
    ports:
      - 30000:30000
      - 30001:30001

volumes:
  k3s-server-vol: { }
