services:
  install-ryax:
    image: ryaxtech/ryax-adm:latest
    entrypoint: /data/local_ryax/k3s-ryax-install.sh
      #entrypoint:
      #  - sleep
      #  - inf
    volumes:
      # This is just so that we get the kubeconfig file in
      - .:/inout
    environment:
      - KUBECONFIG=/inout/kubeconfig.yaml

  kubernetes:
    image: "rancher/k3s:v1.28.2-k3s1"
    command:
      - server
      - --disable=metrics-server
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
      - K3S_TOKEN=InsecureTokEn=ChangeME
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
    volumes:
      - k3s-server-vol:/var/lib/rancher/k3s
      # This is just so that we get the kubeconfig file out
      - .:/output
    ports:
      - 6443:6443  # Kubernetes API Server
      - 80:80      # Ingress controller port 80
      - 443:443    # Ingress controller port 443

  kubernetes-node:
    image: "rancher/k3s:v1.28.2-k3s1"
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
      - K3S_URL=https://kubernetes:6443
      - K3S_TOKEN=InsecureTokEn=ChangeME

volumes:
  k3s-server-vol: { }
