apiVersion: v2
name: authorization
description: The Ryax Authorizaion service manage authentication and user rights inside Ryax.
home: https://ryax.tech
keywords:
  - Ryax
  - Authorization
  - Authentication
  - User management
sources:
  - https://gitlab.com/ryax-tech/ryax/ryax-authorization
icon: https://user-images.githubusercontent.com/104617518/167607288-537e67fb-bbd2-460a-b263-2e4c79b69196.png
version: "26.4.0-rc2"
appVersion: "26.4.0-rc2"
