global:
  # -- Add nodeSelector injected as-is (https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector)
  # @section -- Global
  nodeSelector: {}
  # -- Global container image registry
  # @section -- Global
  imageRegistry:
  # -- Global container registry secret names as an array
  # Example:
  #   - name: myPullSercret
  # @section -- Global
  imagePullSecrets: []
  # --	Global default StorageClass for Persistent Volume(s)
  # @section -- Global
  defaultStorageClass:

  monitoring:
    # -- Enables service monitoring
    # @section -- Global
    enabled: false
    # -- Traces collector (Tempo) endpoint Trace collection (disabled if empty)
    # @section -- Global
    otlpEndpoint: ryax-tempo:4317

  ryax:
    logLevel:
    userNamespace: ryaxns-execs

# -- Name of the secret that contains credentials to access the registry hosting Ryax actions.
# Leave empty to use public access registry
# Secret must be of type: kubernetes.io/dockerconfigjson
actionRegistrySecret: ryax-registry-creds-secret

# -- Ryax Worker configuration use for the registration. See documentation for more details:
# https://docs.ryax.tech/reference/configuration.html#worker-configuration
# @section -- Ryax
config:
  # -- Enable NVIDIA MIG auto-labeler that partition the supported NVIDIA cards 
  MIG:
    enabled: true
  site:
    spec:
      namespace: "{{ .Values.global.ryax.userNamespace }}"

# -- Container images used by the labeler daemonSet
labeler:
  image: bitnamilegacy/kubectl:latest
  pauseImage: k8s.gcr.io/pause:3.1
# 
# -- Resource limit and request for individual user actions if not set in the action `resources` section.
# Requires a LimitRange Kubernetes object. See for more details: https://kubernetes.io/docs/concepts/policy/limit-range/
# @section -- Ryax User Actions Settings
userActionResources:
  request:
    cpu: 0.1
    memory: 64Mi
  limit:
    memory: 64Mi

# -- Rate at which the User Action logging system is queried to get the logs in seconds.
# @section -- Ryax User Actions Settings
actionLogsQueryRate: 5

# -- Activate this to limit users' resource total usage. Highly recommended in production!
# Resource quota for the user namespace set as-is in the Kubernetes ResourceQuota:
# Example:
#   requests.cpu: "2"
#   requests.memory: 2Gi
#   limits.cpu: "16"
#   limits.memory: 32Gi
# See for more details: https://kubernetes.io/docs/concepts/policy/resource-quotas/
# @section -- Resource Settings
userNamespaceResources: {}

# -- container image name and version
image:
  tag: "26.7.0"
  registry: docker.io/ryaxtech
  repository: worker-k8s
  digest: ""
  ## Specify a imagePullPolicy
  ## ref: https://kubernetes.io/docs/concepts/containers/images/#pre-pulled-images
  ##
  pullPolicy: IfNotPresent

# -- log level of the service (override global.ryax.logLevel)
logLevel:
  
# -- Add priority class
priorityClass:

apiPort: 8083
metricsPort: 8092

brokerSecret: ryax-broker-secret

filestoreSecret: ryax-minio-secret
filestoreName: ryax-filestore

# -- Recommended resource requirement
# @section -- Resource Settings
# Example:
#   requests:
#     memory: "2Gi"
#     cpu: "1000m"
#   limits:
#     memory: "2Gi"
resources: {}

# -- Add extra environment variables
extraEnv: []

# -- Add affinity injected as-is (https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity)
# Example:
#   nodeAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: topology.kubernetes.io/zone
#           operator: In
#           values:
#           - antarctica-east1
#           - antarctica-west1
affinity: {}

# -- Use this to override the default postgresql database included in the Helm
databaseURL:

# -- local postgresql database
postgresql:
  # -- Enables PostgreSQL local database
  enabled: true
  auth:
    existingSecret: '{{ include "worker-k8s.postgresql.secret" . }}'
    database: worker_k8s
    username: worker_k8s
  image:
    repository: bitnamilegacy/postgresql
  metrics:
    image:
        repository: bitnamilegacy/postgres-exporter
  primary:
    persistence:
      size: 1Gi
  fullNameOverride: '{{ include "worker-k8s.postgresql.service" . }}'
 
monitoring:
  # -- Enable service monitor for prometheus using ServiceMonitor CRD
  serviceMonitor:
    enabled: true

