{{- $fullname := include "registry.fullname" . }}
{{- if .Values.credentials.enabled }}
{{- $username := .Values.credentials.username | required "credentials.username is required if credentials is enabled" }}
{{- $password := .Values.credentials.password | required "credentials.password is required if credentials is enabled" }}
{{- $hostname := printf "127.0.0.1:%d" (.Values.nodePort | int ) }}
{{- if and .Values.ingress.enabled .Values.ingress.hostname }}
{{- $hostname = .Values.ingress.hostname }}
{{- else if and .Values.ingress.enabled .Values.global.tls.enabled }}
{{- $hostname = printf "%s.%s" "registry" (.Values.global.tls.hostname | required "One of 'global.tls.hostname' or 'ingress.hostname' is required if ingress and credentials are enabled") }}
{{- end }}
{{- $credSecretName := printf "%s-credentials" $fullname }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $credSecretName }}
  labels: {{- include "registry.labels" . | nindent 4 }}
type: Opaque
data:
{{- $secretData := get (lookup "v1" "Secret" .Release.Namespace $credSecretName) "data" | default dict }}
  htpasswd: {{ get $secretData "htpasswd" | default ((htpasswd $username $password) | b64enc) }}
---
{{- $pullSecretCreds :=  printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}, \"%s\": {\"auth\": \"%s\"}}}" $hostname (printf "%s:%s" $username $password | b64enc ) (printf "%s:%d" $fullname (.Values.servicePort | int ) ) (printf "%s:%s" $username $password | b64enc ) | b64enc }}
{{ range $namespace := compact (concat (.Values.credentials.injectInNamespaces) (list .Release.Namespace (.Values.global.ryax.userNamespace | default ""))) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.credentials.pullSecretName }}
  namespace: {{ $namespace }}
  labels: {{- include "registry.labels" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
{{- $secretData := get (lookup "v1" "Secret" $namespace $.Values.credentials.pullSecretName) "data" | default dict }}
  .dockerconfigjson: {{ get $secretData ".dockerconfigjson" | default $pullSecretCreds }}
---
{{- end }}
{{- end }}

{{- if not .Values.ingress.enabled }}
{{- $secretName := printf "%s-cert" $fullname }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels: {{- include "registry.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
{{- $secretData := get (lookup "v1" "Secret" .Release.Namespace $secretName) "data" | default dict }}
{{- $crt := genSelfSignedCert $fullname (list "127.0.0.1") (list "localhost" $fullname) 3650 }}
  tls.crt: {{ get $secretData "tls.crt" | default ($crt.Cert | b64enc | quote) }}
  tls.key: {{ get $secretData "tls.key" | default ($crt.Key | b64enc | quote) }}
{{- end }}
