{{- if .Values.config.MIG.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "worker-k8s.fullname" . }}-gpu-node-labeler
  labels:
    {{- include "worker-k8s.labels" . | nindent 4 }}
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "worker-k8s.fullname" . }}-gpu-node-labeler
  labels:
    {{- include "worker-k8s.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "patch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "worker-k8s.fullname" . }}-gpu-node-labeler
  labels:
    {{- include "worker-k8s.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "worker-k8s.fullname" . }}-gpu-node-labeler
    namespace: {{  .Release.Namespace  }}
roleRef:
  kind: ClusterRole
  name: {{ include "worker-k8s.fullname" . }}-gpu-node-labeler
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "worker-k8s.fullname" . }}-gpu-node-labeler
  labels:
    {{- include "worker-k8s.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "worker-k8s.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "worker-k8s.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app.kubernetes.io/component: "internal"
        ryax.tech/resource-type: "internal"
    spec:
      serviceAccountName: {{ include "worker-k8s.fullname" . }}-gpu-node-labeler
      nodeSelector:
        # Only run this when the device plugin is up
        nvidia.com/gpu.deploy.device-plugin: "true"
      tolerations:
      - effect: NoSchedule
        operator: Exists
      initContainers:
      - name: label-node
        image: {{ .Values.labeler.image }}
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        command:
          - /bin/sh
          - -c
          - |
            #!/bin/sh

            echo "Node name: $NODE_NAME"

            MIG_REQUESTED_CONFIG=$(kubectl get node "$NODE_NAME" -o jsonpath='{.metadata.labels.ryax\.tech/mig\.config"}')
            MIG_CONFIG=$(kubectl get node "$NODE_NAME" -o jsonpath='{.metadata.labels.nvidia\.com/mig\.config"}')
            MIG_STATE=$(kubectl get node "$NODE_NAME" -o jsonpath='{.metadata.labels.nvidia\.com/mig\.config\.state"}')

            echo "Ryax MIG Configuration
            echo "Requested:\t $MIG_REQUESTED_CONFIG
            echo "Found: \t $MIG_CONFIG
            echo "Status:\t $MIG_STATE"

            if [ "$MIG_CONFIG" == "$MIG_REQUESTED_CONFIG" ] && [ "$MIG_STATE" == "failed"]
            then
                echo "Reset node pool MIG to all-disabled"
                kubectl label node "$NODE_NAME" "nvidia.com/mig.config=all-disabled" --overwrite
            fi
            if [ "$MIG_CONFIG" != "$MIG_REQUESTED_CONFIG" ]
                echo "Patch success for $NODE_NAME : $MIG_CONFIG"
                kubectl label node "$NODE_NAME" "nvidia.com/mig.config=$MIG_REQUESTED_CONFIG" --overwrite
            fi
            
            until [ $(kubectl get node "$NODE_NAME" -o jsonpath='{.metadata.labels.nvidia\.com/mig\.config\.state"}') == "success" ]
            do
                echo Current MIG state: $(kubectl get node "$NODE_NAME" -o jsonpath='{.metadata.labels.nvidia\.com/mig\.config\.state"}')
            done
                echo "$NODE_NAME, is now comfigured with $MIG_CONFIG"
            fi
      containers:
        - name: pause-container
          image: {{ .Values.labeler.pauseImage }}
{{- end }}
