{{- if .Values.postgresql.enabled }}
{{- $secretName := include "worker-k8s.postgresql.secret" . }}
{{- $secretData := get (lookup "v1" "Secret" .Release.Namespace $secretName) "data" | default dict }}
{{- $password := get $secretData "password" | b64dec | default .Values.postgresql.auth.password | default (randAlphaNum 12) }}
{{- $pgPassword := get $secretData "postgres-password" | b64dec | default .Values.postgresql.auth.postgresPassword | default (randAlphaNum 12) }}
---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ $secretName }}
  labels: {{ include "worker-k8s.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
type: "Opaque"
data:
  password: {{ $password  | b64enc }}
  postgres-password: {{ $pgPassword  | b64enc }}
  datastore-worker-k8s: {{ printf "postgresql://worker_k8s:%s@%s/worker_k8s" $password (include "worker-k8s.postgresql.service" .) | b64enc }}
{{- end }}
