{{- $secretData := get (lookup "v1" "Secret" .Release.Namespace .Values.datastoreSecret) "data" | default dict }}
{{- $datastorePass := get $secretData "datastore-pass" | b64dec | default (randAlphaNum 12) }}
{{- $datastoreUrl := printf "postgresql://%s:%s@%s/%s" .Values.datastoreUser $datastorePass (include "datastore.fullname" .) .Values.datastoreDB }}
---
apiVersion: "v1"
kind: "Secret"
type: "Opaque"
metadata:
  name: {{ .Values.datastoreSecret }}
  labels: {{ include "datastore.labels" . | nindent 4 }}
stringData:
  {{- if .Values.global.monitoring.enabled }}
  # comma separated list of all databases for prometheus, except the default
  # database is enough to scrape data from everywhere
  all-databases: {{ printf "%s?sslmode=disable" $datastoreUrl }}
  {{- end }}
  datastore: {{ $datastoreUrl }}
  datastore-db: {{ .Values.datastoreDB }}
  datastore-user: {{ .Values.datastoreUser }}
  datastore-pass: {{ $datastorePass }}
{{- range .Values.databases }}
  {{- $datastorePass := printf "datastore-%s-pass" . | get $secretData | b64dec | default (randAlphaNum 12) }}
  {{ printf "datastore-%s-user" . }}: {{ . }}
  {{ printf "datastore-%s-db" . }}: {{ . }}
  {{ printf "datastore-%s-pass" . }}: {{ $datastorePass }}
  {{ printf "datastore-%s" . }}: {{ printf "postgresql://%s:%s@%s/%s" . $datastorePass (include "datastore.fullname" $) . }}
{{- end }}

