apiVersion: "v1"
kind: "Service"
metadata:
  labels: {{ include "datastore.labels" . | nindent 4 }}
    exporter: '0'
  name: {{ include "datastore.fullname" . }}
spec:
  ports:
    - port: {{ .Values.servicePort }}
  selector: {{ include "datastore.selectorLabels" . | nindent 4 }}
    exporter: '0'

{{- if .Values.global.monitoring.enabled }}
---
apiVersion: "v1"
kind: "Service"
metadata:
  labels: {{ include "datastore.labels" . | nindent 4 }}
    exporter: '1'
  name: {{ include "datastore.fullname" . | printf "%s-exporter" }}
spec:
  ports:
    - name: "metrics"
      port: 9187
  selector: {{ include "datastore.selectorLabels" . | nindent 4 }}
    exporter: '1'
{{- end }}
