{{- if .Values.hpcPrivateKeyFile }}
apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ include "worker.fullname" . }}-hpc-key
  labels: {{ include "worker.labels" . | nindent 4 }}
type: "Opaque"
data:
  id_rsa: {{ .Values.hpcPrivateKeyFile | b64enc }}
  {{- if .Values.hpcSSHConfig }}
  config: {{ .Values.hpcSSHConfig | b64enc }}
  {{- end }}
{{- end }}
{{- if .Values.postgresql.enabled }}
{{- $secretName := include "worker.postgresql.secret" . }}
{{- $secretData := get (lookup "v1" "Secret" .Release.Namespace $secretName) "data" | default dict }}
{{- $password := get $secretData "password" | b64dec | default .Values.postgresql.auth.password | default (randAlphaNum 12) }}
{{- $pgPassword := get $secretData "postgres-password" | b64dec | default .Values.postgresql.auth.postgresPassword | default (randAlphaNum 12) }}
---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ $secretName }}
  labels: {{ include "worker.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
type: "Opaque"
data:
  password: {{ $password  | b64enc }}
  postgres-password: {{ $pgPassword  | b64enc }}
  datastore-worker: {{ printf "postgresql://worker:%s@%s/worker" $password (include "worker.postgresql.service" .) | b64enc }}
{{- end }}
