apiVersion: "v1"
kind: "Service"
metadata:
  name: {{ .Release.Name }}
  labels: {{- include "worker.labels" . | nindent 4 }}
spec:
  ports:
    - name: "api"
      port: {{ .Values.apiPort }}
    - name: "metrics"
      port: {{ .Values.metricsPort }}
  selector: {{- include "worker.selectorLabels" . | nindent 4 }}
