# This is required by the HTTP service addon that needs to create and delete Ingress, Service and Middleware on the fly
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "runner.fullname" . }}
  labels: {{- include "runner.labels" . | nindent 4}}
rules:
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - traefik.io
  resources:
  - middlewares
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "runner.fullname" . }}
  labels: {{- include "runner.labels" . | nindent 4}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "runner.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "runner.fullname" . }}
  namespace: {{ .Release.Namespace }}
