apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ .Values.encryptionKeySecret }}
  labels: {{ include "runner.labels" . | nindent 4 }}
type: "Opaque"
stringData:
  {{- $secretData := get (lookup "v1" "Secret" .Release.Namespace .Values.encryptionKeySecret) "data" | default dict }}
  encryption-key: {{ get $secretData "encryption-key" | b64dec | default .Values.fernetEncryptionKey | default (randAscii 32 | b64enc) }}
---
{{- if .Values.billing.enabled }}
apiVersion: "v1"
kind: "Secret"
metadata:
  name: stripe-secrets
  labels: {{ include "runner.labels" . | nindent 4 }}
type: "Opaque"
data:
  stripe-api-key: {{ .Values.billing.stripe_api_key | b64enc }}
  stripe-customer-id: {{ .Values.billing.stripe_customer_id | b64enc }}
{{- end }}
