{{- if .Values.hpcPrivateKeyFile }}
apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ include "worker-ssh-slurm.fullname" . }}-hpc-key
  labels: {{ include "worker-ssh-slurm.labels" . | nindent 4 }}
type: "Opaque"
data:
  id_rsa: {{ .Values.hpcPrivateKeyFile | b64enc }}
  {{- if .Values.hpcSSHConfig }}
  config: {{ .Values.hpcSSHConfig | b64enc }}
  {{- end }}
{{- end }}
{{- if and .Values.postgresql.enabled .Values.global.secrets.create .Values.postgresql.auth.createSecret }}
{{- $secretName := include "worker-ssh-slurm.postgresql.secret" . }}
{{- $secretData := get (lookup "v1" "Secret" .Release.Namespace $secretName) "data" | default dict }}
{{- $password := get $secretData "password" | b64dec | default .Values.postgresql.auth.password | default (randAlphaNum 12) }}
{{- $pgPassword := get $secretData "postgres-password" | b64dec | default .Values.postgresql.auth.postgresPassword | default (randAlphaNum 12) }}
---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ $secretName }}
  labels: {{ include "worker-ssh-slurm.labels" . | nindent 4 }}
type: "Opaque"
data:
  password: {{ $password  | b64enc }}
  postgres-password: {{ $pgPassword  | b64enc }}
  datastore-worker-ssh-slurm: {{ printf "postgresql://worker-ssh-slurm:%s@%s/worker-ssh-slurm" $password (include "worker-ssh-slurm.postgresql.service" .) | b64enc }}
{{- end }}
