# -- Special config for k3s
global:
  imagePullPolicy: IfNotPresent
  defaultStorageClass: local-path
  tls:
    enabled: false

action-builder:
  extraEnv:
    - name: RYAX_NIX_GARBAGE_COLLECT_ENABLED
      value: "false"

worker:
  config:
    site:
      name: local
      spec:
        namespace: ryaxns-execs
        nodePools:
        - cpu: 4
          memory: 8G
          name: default
          selector:
            node.kubernetes.io/instance-type: k3s
      type: KUBERNETES

traefik:
  # traefik is already deployed by default in k3s
  deployment:
    enabled: false
